# .gitlab-ci.yml
image: maven:3.9-eclipse-temurin-21

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile -B

test:
  stage: test
  script:
    - mvn test -B