version: '3.8'

services:
  # Приложение Spring Boot
  finance-tracker:
    build: .
    image: finance-tracker:latest
    container_name: finance-tracker-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: finance_user
      SPRING_DATASOURCE_PASSWORD: finance_pass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - prometheus
      - redis
    networks:
      - monitoring_net

  # База данных PostgreSQL
  postgres:
    image: postgres:15
    container_name: finance-postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring_net

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring_net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: false
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    networks:
      - monitoring_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - monitoring_net

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  monitoring_net:
    driver: bridge