spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ssXXX"
  datasource:
    url: jdbc:postgresql://postgres:5432/finance_db
    username: finance_user
    password: finance_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    # ??????? ddl-auto, Flyway ????????? ??????
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway ????????? (???????????, ???????? ?? ????????? ?????? ????????)
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true